### ISSUE TITLE
MYC: Bug in date editing causing edits not to publish even when they pass validation rules

### ISSUE THREAD

**Issue by mentionthewar** [nationalarchives/manage-your-collections#2] opened 2019-01-17 16:17 UTC
This affects live editing in Discovery. The validation rules seem to have been implemented in such a way that even valid formats fail.

**Comment by ACTNA** [comment] 2019-02-19 10:30
Clicked the wrong button! Closed the issue rather than closed the window. Moving back to issue list.

**Comment by CarolD** [comment] 2019-03-14 07:29
I'll need the details of the data that caused this issue so I can replicate and test with it

**Comment by CarolD** [comment] 2019-03-14 13:37
I've spoken to Jo and he sayes this doesn't appear to be an issue now.
Now there was an issue a little while back that a javascript function was stopping being able to publish and the workaround was that Mihai did a fix to the javascript for this. I can't remember when this one went to production, I've got a feeling it was a while in test before it went live. So it could be this was the issue and it's now resolved. 
Unless anyone has any objections I think this one can be closed for now.

**Comment by mcieslak** [comment] 2019-03-18 11:26
Closing this (as per Carol's instruction...)

**Comment by CarolD** [comment] 2019-04-04 13:20
Over the past week or so, I've seen instances of this that makes me believe that there is another issue that is causing 'stuck' in publishing, so I feel this should now be reopened.
Over the lifetime of the system in the application logs I can see 12 stuck in publishing events, while some of the earlier ones may be the other issue, there are 5 this year that probably won't be. 
I looked at one, when I put it back to the preview stage it could then be approved successfully.  
It needs further investigation but I got the impression it was to do with not being able to update the Discovery database, maybe it timed out if it was busy so was more performance related when doing bulk updates. But need to look at the other examples and the logs more.

**Comment by CarolD** [comment] 2019-04-24 07:32
I've looked at all the data that stuck on publishing and tried it in test and it all worked fine, there's no errors generated and I can see no reason why it might happen in occasion. I've put in extra logging that could help see where in the process it happens and I suggest next time it happens if we roll it back a stage so they can retry the approval.

**Comment by CarolD** [comment] 2019-04-24 07:33
think this could be closed

**Comment by CarolD** [comment] 2019-06-19 15:32
the root cause as issue 10

**Closed as completed by CarolD** 2019-06-19 15:32 UTC
Labels: bug
